// Catalog of local-runnable open models.
// Quant file sizes are real — pulled from GGUF mirrors on Hugging Face (bartowski/unsloth/etc.),
// not estimated. requiredGB = fileGB + max(1.5, fileGB * 0.15), rounded to 1 decimal — the
// runtime/context overhead on top of the raw file, applied consistently across every entry.
//
// context: the model's trained context window in tokens, read from each model's own config.json
// (max_position_embeddings) where the repo is accessible. A few families (Llama, Gemma 2,
// Code Llama, Command R) are access-gated on Hugging Face even for config.json, so those use
// the officially published spec instead of a live read — same number, just not a live fetch.
//
// ollamaTag: the exact tag for `ollama pull <ollamaTag>`, verified against ollama.com's own
// tag listings and (where ambiguous, e.g. Code Llama's base/instruct/python split) cross-checked
// against the HF repo the tag's page links back to. Omitted when no matching tag actually exists
// at this size (see qwen2-vl-2b) rather than guessing one.
//
// benchmarks[]: pulled from each model's own Hugging Face model card where available.
// Entries flagged `secondary: true` come from another model's published comparison table
// (several source cards are access-gated on HF or link to an external blog instead of a table),
// not the model's own card — flagged with a † in the UI. Some models carry no benchmarks at all
// rather than a guess, when nothing extractable was found.
//
// Vision models (LLaVA, Qwen2-VL) also need a separate mmproj (vision projector) file to actually
// do vision — that file isn't counted in the fileGB/requiredGB numbers below.

const MODELS = [
  {
    id: "llama32-1b",
    name: "Llama 3.2",
    params: "1B",
    paramsB: 1,
    family: "Llama",
    context: 131072,
    benchmarks: [],
    blurb: "Fast and small. Good for quick edits and simple chat, not deep reasoning.",
    tags: ["writing", "chat", "general"],
    quants: [
      { quant: "Q4_K_M", fileGB: 0.8, requiredGB: 2.3 },
      { quant: "Q8_0", fileGB: 1.3, requiredGB: 2.8 },
    ],
    runtimes: ["Ollama", "llama.cpp", "MLX"],
    ollamaTag: "llama3.2:1b",
    links: {
      github: "https://github.com/meta-llama/llama-models",
      huggingface: "https://huggingface.co/meta-llama/Llama-3.2-1B-Instruct",
      ollama: "https://ollama.com/library/llama3.2",
    },
  },
  {
    id: "llama32-3b",
    name: "Llama 3.2",
    params: "3B",
    paramsB: 3,
    family: "Llama",
    context: 131072,
    benchmarks: [
      { area: "research", benchmark: "MMLU", score: "61.8", note: "5-shot", secondary: true },
      { area: "chat", benchmark: "Arena-Hard", score: "17.0", note: "", secondary: true },
      { area: "research", benchmark: "GPQA", score: "24.3", note: "0-shot, CoT", secondary: true },
    ],
    blurb: "A step up in coherence over the 1B — still light enough for laptops.",
    tags: ["writing", "chat", "general"],
    quants: [
      { quant: "Q4_K_M", fileGB: 2.0, requiredGB: 3.5 },
      { quant: "Q8_0", fileGB: 3.4, requiredGB: 4.9 },
    ],
    runtimes: ["Ollama", "llama.cpp", "MLX"],
    ollamaTag: "llama3.2:3b",
    links: {
      github: "https://github.com/meta-llama/llama-models",
      huggingface: "https://huggingface.co/meta-llama/Llama-3.2-3B-Instruct",
      ollama: "https://ollama.com/library/llama3.2",
    },
  },
  {
    id: "llama31-8b",
    name: "Llama 3.1",
    params: "8B",
    paramsB: 8,
    family: "Llama",
    context: 131072,
    benchmarks: [
      { area: "research", benchmark: "MMLU", score: "69.4", note: "5-shot" },
      { area: "coding", benchmark: "HumanEval", score: "72.6", note: "pass@1" },
      { area: "writing", benchmark: "IFEval", score: "80.4", note: "" },
    ],
    blurb: "Solid general-purpose model — the reasonable default for chat and writing.",
    tags: ["writing", "chat", "general", "research"],
    quants: [
      { quant: "Q4_K_M", fileGB: 4.9, requiredGB: 6.4 },
      { quant: "Q8_0", fileGB: 8.5, requiredGB: 10.0 },
    ],
    runtimes: ["Ollama", "llama.cpp", "LM Studio", "MLX"],
    ollamaTag: "llama3.1:8b",
    links: {
      github: "https://github.com/meta-llama/llama-models",
      huggingface: "https://huggingface.co/meta-llama/Llama-3.1-8B-Instruct",
      ollama: "https://ollama.com/library/llama3.1",
    },
  },
  {
    id: "llama31-70b",
    name: "Llama 3.1",
    params: "70B",
    paramsB: 70,
    family: "Llama",
    context: 131072,
    benchmarks: [],
    blurb: "The largest Llama 3.1 tier — near frontier quality, but needs serious hardware to run locally.",
    tags: ["research", "writing", "general"],
    quants: [
      { quant: "Q4_K_M", fileGB: 42.5, requiredGB: 48.9 },
    ],
    runtimes: ["Ollama", "llama.cpp", "LM Studio", "MLX"],
    ollamaTag: "llama3.1:70b",
    links: {
      github: "https://github.com/meta-llama/llama-models",
      huggingface: "https://huggingface.co/meta-llama/Llama-3.1-70B-Instruct",
      ollama: "https://ollama.com/library/llama3.1",
    },
  },

  {
    id: "qwen25-05b",
    name: "Qwen2.5",
    params: "0.5B",
    paramsB: 0.5,
    family: "Qwen",
    context: 32768,
    benchmarks: [],
    blurb: "Tiny and near-instant — good for quick lookups, not nuanced writing.",
    tags: ["writing", "chat", "general"],
    quants: [
      { quant: "Q4_K_M", fileGB: 0.4, requiredGB: 1.9 },
      { quant: "Q8_0", fileGB: 0.5, requiredGB: 2.0 },
    ],
    runtimes: ["Ollama", "llama.cpp", "LM Studio", "MLX"],
    ollamaTag: "qwen2.5:0.5b",
    links: {
      github: "https://github.com/QwenLM/Qwen2.5",
      huggingface: "https://huggingface.co/Qwen/Qwen2.5-0.5B-Instruct",
      ollama: "https://ollama.com/library/qwen2.5",
    },
  },
  {
    id: "qwen25-15b",
    name: "Qwen2.5",
    params: "1.5B",
    paramsB: 1.5,
    family: "Qwen",
    context: 32768,
    benchmarks: [],
    blurb: "A step up from the 0.5B with more reliable instruction following.",
    tags: ["writing", "chat", "general"],
    quants: [
      { quant: "Q4_K_M", fileGB: 1.0, requiredGB: 2.5 },
      { quant: "Q8_0", fileGB: 1.6, requiredGB: 3.1 },
    ],
    runtimes: ["Ollama", "llama.cpp", "LM Studio", "MLX"],
    ollamaTag: "qwen2.5:1.5b",
    links: {
      github: "https://github.com/QwenLM/Qwen2.5",
      huggingface: "https://huggingface.co/Qwen/Qwen2.5-1.5B-Instruct",
      ollama: "https://ollama.com/library/qwen2.5",
    },
  },
  {
    id: "qwen25-3b",
    name: "Qwen2.5",
    params: "3B",
    paramsB: 3,
    family: "Qwen",
    context: 32768,
    benchmarks: [
      { area: "research", benchmark: "MMLU", score: "65.0", note: "5-shot", secondary: true },
      { area: "chat", benchmark: "Arena-Hard", score: "32.0", note: "", secondary: true },
      { area: "research", benchmark: "GPQA", score: "23.4", note: "0-shot, CoT", secondary: true },
    ],
    blurb: "Noticeably steadier reasoning than the 1.5B, still runs on modest hardware.",
    tags: ["writing", "chat", "general"],
    quants: [
      { quant: "Q4_K_M", fileGB: 1.9, requiredGB: 3.4 },
      { quant: "Q8_0", fileGB: 3.3, requiredGB: 4.8 },
    ],
    runtimes: ["Ollama", "llama.cpp", "LM Studio", "MLX"],
    ollamaTag: "qwen2.5:3b",
    links: {
      github: "https://github.com/QwenLM/Qwen2.5",
      huggingface: "https://huggingface.co/Qwen/Qwen2.5-3B-Instruct",
      ollama: "https://ollama.com/library/qwen2.5",
    },
  },
  {
    id: "qwen25-7b",
    name: "Qwen2.5",
    params: "7B",
    paramsB: 7,
    family: "Qwen",
    context: 32768,
    benchmarks: [
      { area: "research", benchmark: "MMLU", score: "72.6", note: "5-shot", secondary: true },
      { area: "chat", benchmark: "Arena-Hard", score: "55.5", note: "", secondary: true },
      { area: "research", benchmark: "GPQA", score: "30.6", note: "0-shot, CoT", secondary: true },
    ],
    blurb: "Strong all-rounder with long context — a good research and writing default.",
    tags: ["writing", "research", "general", "chat"],
    quants: [
      { quant: "Q4_K_M", fileGB: 4.7, requiredGB: 6.2 },
      { quant: "Q8_0", fileGB: 8.1, requiredGB: 9.6 },
    ],
    runtimes: ["Ollama", "llama.cpp", "LM Studio", "MLX"],
    ollamaTag: "qwen2.5:7b",
    links: {
      github: "https://github.com/QwenLM/Qwen2.5",
      huggingface: "https://huggingface.co/Qwen/Qwen2.5-7B-Instruct",
      ollama: "https://ollama.com/library/qwen2.5",
    },
  },
  {
    id: "qwen25-14b",
    name: "Qwen2.5",
    params: "14B",
    paramsB: 14,
    family: "Qwen",
    context: 32768,
    benchmarks: [
      { area: "research", benchmark: "MMLU", score: "79.9", note: "", secondary: true },
      { area: "coding", benchmark: "HumanEval", score: "72.1", note: "", secondary: true },
    ],
    blurb: "More headroom for longer research documents and multi-step reasoning.",
    tags: ["research", "writing", "general"],
    quants: [
      { quant: "Q4_K_M", fileGB: 9.0, requiredGB: 10.5 },
      { quant: "Q8_0", fileGB: 15.7, requiredGB: 18.1 },
    ],
    runtimes: ["Ollama", "llama.cpp", "LM Studio"],
    ollamaTag: "qwen2.5:14b",
    links: {
      github: "https://github.com/QwenLM/Qwen2.5",
      huggingface: "https://huggingface.co/Qwen/Qwen2.5-14B-Instruct",
      ollama: "https://ollama.com/library/qwen2.5",
    },
  },
  {
    id: "qwen25-32b",
    name: "Qwen2.5",
    params: "32B",
    paramsB: 32,
    family: "Qwen",
    context: 32768,
    benchmarks: [],
    blurb: "One of the strongest models you can still self-host on a single high-VRAM GPU.",
    tags: ["research", "writing"],
    quants: [
      { quant: "Q4_K_M", fileGB: 19.9, requiredGB: 22.9 },
      { quant: "Q8_0", fileGB: 34.8, requiredGB: 40.0 },
    ],
    runtimes: ["Ollama", "llama.cpp", "LM Studio"],
    ollamaTag: "qwen2.5:32b",
    links: {
      github: "https://github.com/QwenLM/Qwen2.5",
      huggingface: "https://huggingface.co/Qwen/Qwen2.5-32B-Instruct",
      ollama: "https://ollama.com/library/qwen2.5",
    },
  },
  {
    id: "qwen25-72b",
    name: "Qwen2.5",
    params: "72B",
    paramsB: 72,
    family: "Qwen",
    context: 32768,
    benchmarks: [
      { area: "research", benchmark: "MMLU", score: "85.3", note: "", secondary: true },
      { area: "coding", benchmark: "HumanEval", score: "80.4", note: "", secondary: true },
    ],
    blurb: "Flagship-class quality. Realistically needs multi-GPU or a large unified-memory Mac.",
    tags: ["research", "writing"],
    quants: [
      { quant: "Q4_K_M", fileGB: 47.4, requiredGB: 54.5 },
    ],
    runtimes: ["Ollama", "llama.cpp"],
    ollamaTag: "qwen2.5:72b",
    links: {
      github: "https://github.com/QwenLM/Qwen2.5",
      huggingface: "https://huggingface.co/Qwen/Qwen2.5-72B-Instruct",
      ollama: "https://ollama.com/library/qwen2.5",
    },
  },

  {
    id: "qwen25-coder-05b",
    name: "Qwen2.5 Coder",
    params: "0.5B",
    paramsB: 0.5,
    family: "Qwen",
    context: 32768,
    benchmarks: [],
    blurb: "Barely a gigabyte — useful for inline completions, not complex refactors.",
    tags: ["coding", "agents"],
    quants: [
      { quant: "Q4_K_M", fileGB: 0.4, requiredGB: 1.9 },
      { quant: "Q8_0", fileGB: 0.5, requiredGB: 2.0 },
    ],
    runtimes: ["Ollama", "llama.cpp", "LM Studio"],
    ollamaTag: "qwen2.5-coder:0.5b",
    links: {
      github: "https://github.com/QwenLM/Qwen2.5-Coder",
      huggingface: "https://huggingface.co/Qwen/Qwen2.5-Coder-0.5B-Instruct",
      ollama: "https://ollama.com/library/qwen2.5-coder",
    },
  },
  {
    id: "qwen25-coder-15b",
    name: "Qwen2.5 Coder",
    params: "1.5B",
    paramsB: 1.5,
    family: "Qwen",
    context: 32768,
    benchmarks: [],
    blurb: "A small step up for slightly more reliable completions on modest hardware.",
    tags: ["coding", "agents"],
    quants: [
      { quant: "Q4_K_M", fileGB: 1.0, requiredGB: 2.5 },
      { quant: "Q8_0", fileGB: 1.6, requiredGB: 3.1 },
    ],
    runtimes: ["Ollama", "llama.cpp", "LM Studio"],
    ollamaTag: "qwen2.5-coder:1.5b",
    links: {
      github: "https://github.com/QwenLM/Qwen2.5-Coder",
      huggingface: "https://huggingface.co/Qwen/Qwen2.5-Coder-1.5B-Instruct",
      ollama: "https://ollama.com/library/qwen2.5-coder",
    },
  },
  {
    id: "qwen25-coder-3b",
    name: "Qwen2.5 Coder",
    params: "3B",
    paramsB: 3,
    family: "Qwen",
    context: 32768,
    benchmarks: [],
    blurb: "Handles single-file completions comfortably on a laptop.",
    tags: ["coding", "agents"],
    quants: [
      { quant: "Q4_K_M", fileGB: 1.9, requiredGB: 3.4 },
      { quant: "Q8_0", fileGB: 3.3, requiredGB: 4.8 },
    ],
    runtimes: ["Ollama", "llama.cpp", "LM Studio"],
    ollamaTag: "qwen2.5-coder:3b",
    links: {
      github: "https://github.com/QwenLM/Qwen2.5-Coder",
      huggingface: "https://huggingface.co/Qwen/Qwen2.5-Coder-3B-Instruct",
      ollama: "https://ollama.com/library/qwen2.5-coder",
    },
  },
  {
    id: "qwen25-coder-7b",
    name: "Qwen2.5 Coder",
    params: "7B",
    paramsB: 7,
    family: "Qwen",
    context: 32768,
    benchmarks: [],
    blurb: "Purpose-built for code completion and refactors at laptop-friendly size.",
    tags: ["coding", "agents"],
    quants: [
      { quant: "Q4_K_M", fileGB: 4.7, requiredGB: 6.2 },
      { quant: "Q8_0", fileGB: 8.1, requiredGB: 9.6 },
    ],
    runtimes: ["Ollama", "llama.cpp", "LM Studio"],
    ollamaTag: "qwen2.5-coder:7b",
    links: {
      github: "https://github.com/QwenLM/Qwen2.5-Coder",
      huggingface: "https://huggingface.co/Qwen/Qwen2.5-Coder-7B-Instruct",
      ollama: "https://ollama.com/library/qwen2.5-coder",
    },
  },
  {
    id: "qwen25-coder-14b",
    name: "Qwen2.5 Coder",
    params: "14B",
    paramsB: 14,
    family: "Qwen",
    context: 32768,
    benchmarks: [],
    blurb: "Noticeably better at multi-file reasoning than the 7B, still runs on one GPU.",
    tags: ["coding", "agents"],
    quants: [
      { quant: "Q4_K_M", fileGB: 9.0, requiredGB: 10.5 },
      { quant: "Q8_0", fileGB: 15.7, requiredGB: 18.1 },
    ],
    runtimes: ["Ollama", "llama.cpp", "LM Studio"],
    ollamaTag: "qwen2.5-coder:14b",
    links: {
      github: "https://github.com/QwenLM/Qwen2.5-Coder",
      huggingface: "https://huggingface.co/Qwen/Qwen2.5-Coder-14B-Instruct",
      ollama: "https://ollama.com/library/qwen2.5-coder",
    },
  },
  {
    id: "qwen25-coder-32b",
    name: "Qwen2.5 Coder",
    params: "32B",
    paramsB: 32,
    family: "Qwen",
    context: 32768,
    benchmarks: [],
    blurb: "Near frontier-level coding quality — needs a real workstation GPU or a lot of RAM.",
    tags: ["coding", "agents"],
    quants: [
      { quant: "Q4_K_M", fileGB: 19.9, requiredGB: 22.9 },
      { quant: "Q8_0", fileGB: 34.8, requiredGB: 40.0 },
    ],
    runtimes: ["Ollama", "llama.cpp", "LM Studio"],
    ollamaTag: "qwen2.5-coder:32b",
    links: {
      github: "https://github.com/QwenLM/Qwen2.5-Coder",
      huggingface: "https://huggingface.co/Qwen/Qwen2.5-Coder-32B-Instruct",
      ollama: "https://ollama.com/library/qwen2.5-coder",
    },
  },

  {
    id: "deepseek-r1-qwen-15b",
    name: "DeepSeek-R1 Distill (Qwen)",
    params: "1.5B",
    paramsB: 1.5,
    family: "DeepSeek",
    context: 131072,
    benchmarks: [
      { area: "research", benchmark: "GPQA Diamond", score: "33.8", note: "pass@1" },
      { area: "coding", benchmark: "LiveCodeBench", score: "16.9", note: "pass@1" },
    ],
    blurb: "The smallest reasoning distill — shows its work, but least capable of the family.",
    tags: ["research", "coding"],
    quants: [
      { quant: "Q4_K_M", fileGB: 1.1, requiredGB: 2.6 },
      { quant: "Q8_0", fileGB: 1.9, requiredGB: 3.4 },
    ],
    runtimes: ["Ollama", "llama.cpp"],
    ollamaTag: "deepseek-r1:1.5b",
    links: {
      github: "https://github.com/deepseek-ai/DeepSeek-R1",
      huggingface: "https://huggingface.co/deepseek-ai/DeepSeek-R1-Distill-Qwen-1.5B",
      ollama: "https://ollama.com/library/deepseek-r1",
    },
  },
  {
    id: "deepseek-r1-qwen-7b",
    name: "DeepSeek-R1 Distill (Qwen)",
    params: "7B",
    paramsB: 7,
    family: "DeepSeek",
    context: 131072,
    benchmarks: [
      { area: "research", benchmark: "GPQA Diamond", score: "49.1", note: "pass@1" },
      { area: "coding", benchmark: "LiveCodeBench", score: "37.6", note: "pass@1" },
    ],
    blurb: "Shows its reasoning step by step — good for math and logic-heavy questions.",
    tags: ["research", "coding"],
    quants: [
      { quant: "Q4_K_M", fileGB: 4.7, requiredGB: 6.2 },
      { quant: "Q8_0", fileGB: 8.1, requiredGB: 9.6 },
    ],
    runtimes: ["Ollama", "llama.cpp"],
    ollamaTag: "deepseek-r1:7b",
    links: {
      github: "https://github.com/deepseek-ai/DeepSeek-R1",
      huggingface: "https://huggingface.co/deepseek-ai/DeepSeek-R1-Distill-Qwen-7B",
      ollama: "https://ollama.com/library/deepseek-r1",
    },
  },
  {
    id: "deepseek-r1-qwen-14b",
    name: "DeepSeek-R1 Distill (Qwen)",
    params: "14B",
    paramsB: 14,
    family: "DeepSeek",
    context: 131072,
    benchmarks: [
      { area: "research", benchmark: "GPQA Diamond", score: "59.1", note: "pass@1" },
      { area: "coding", benchmark: "LiveCodeBench", score: "53.1", note: "pass@1" },
    ],
    blurb: "Better reasoning depth than the 7B distill, still fits on a single mid-range GPU.",
    tags: ["research", "coding"],
    quants: [
      { quant: "Q4_K_M", fileGB: 9.0, requiredGB: 10.5 },
      { quant: "Q8_0", fileGB: 15.7, requiredGB: 18.1 },
    ],
    runtimes: ["Ollama", "llama.cpp"],
    ollamaTag: "deepseek-r1:14b",
    links: {
      github: "https://github.com/deepseek-ai/DeepSeek-R1",
      huggingface: "https://huggingface.co/deepseek-ai/DeepSeek-R1-Distill-Qwen-14B",
      ollama: "https://ollama.com/library/deepseek-r1",
    },
  },
  {
    id: "deepseek-r1-qwen-32b",
    name: "DeepSeek-R1 Distill (Qwen)",
    params: "32B",
    paramsB: 32,
    family: "DeepSeek",
    context: 131072,
    benchmarks: [
      { area: "research", benchmark: "GPQA Diamond", score: "62.1", note: "pass@1" },
      { area: "coding", benchmark: "LiveCodeBench", score: "57.2", note: "pass@1" },
    ],
    blurb: "The strongest distill — outperforms OpenAI o1-mini on several reasoning benchmarks per DeepSeek's own report.",
    tags: ["research", "coding"],
    quants: [
      { quant: "Q4_K_M", fileGB: 19.9, requiredGB: 22.9 },
      { quant: "Q8_0", fileGB: 34.8, requiredGB: 40.0 },
    ],
    runtimes: ["Ollama", "llama.cpp"],
    ollamaTag: "deepseek-r1:32b",
    links: {
      github: "https://github.com/deepseek-ai/DeepSeek-R1",
      huggingface: "https://huggingface.co/deepseek-ai/DeepSeek-R1-Distill-Qwen-32B",
      ollama: "https://ollama.com/library/deepseek-r1",
    },
  },
  {
    id: "deepseek-r1-llama-8b",
    name: "DeepSeek-R1 Distill (Llama)",
    params: "8B",
    paramsB: 8,
    family: "DeepSeek",
    context: 131072,
    benchmarks: [
      { area: "research", benchmark: "GPQA Diamond", score: "49.0", note: "pass@1" },
      { area: "coding", benchmark: "LiveCodeBench", score: "39.6", note: "pass@1" },
    ],
    blurb: "Reasoning-tuned distillation of Llama 3.1 — a lighter alternative to the Qwen distill.",
    tags: ["research", "coding"],
    quants: [
      { quant: "Q4_K_M", fileGB: 4.9, requiredGB: 6.4 },
      { quant: "Q8_0", fileGB: 8.5, requiredGB: 10.0 },
    ],
    runtimes: ["Ollama", "llama.cpp"],
    ollamaTag: "deepseek-r1:8b",
    links: {
      github: "https://github.com/deepseek-ai/DeepSeek-R1",
      huggingface: "https://huggingface.co/deepseek-ai/DeepSeek-R1-Distill-Llama-8B",
      ollama: "https://ollama.com/library/deepseek-r1",
    },
  },

  {
    id: "mistral-7b",
    name: "Mistral",
    params: "7B",
    paramsB: 7,
    family: "Mistral",
    context: 32768,
    benchmarks: [
      { area: "writing", benchmark: "MMLU", score: "60.3", note: "5-shot", secondary: true },
      { area: "chat", benchmark: "Arena-Hard", score: "18.1", note: "", secondary: true },
    ],
    blurb: "Dependable, well-rounded writing model with a permissive license.",
    tags: ["writing", "chat", "general"],
    quants: [
      { quant: "Q4_K_M", fileGB: 4.4, requiredGB: 5.9 },
      { quant: "Q8_0", fileGB: 7.7, requiredGB: 9.2 },
    ],
    runtimes: ["Ollama", "llama.cpp", "LM Studio"],
    ollamaTag: "mistral:7b",
    links: {
      github: "https://github.com/mistralai/mistral-inference",
      huggingface: "https://huggingface.co/mistralai/Mistral-7B-Instruct-v0.3",
      ollama: "https://ollama.com/library/mistral",
    },
  },
  {
    id: "mistral-nemo-12b",
    name: "Mistral Nemo",
    params: "12B",
    paramsB: 12,
    family: "Mistral",
    context: 131072,
    benchmarks: [
      { area: "writing", benchmark: "MMLU", score: "68.0", note: "5-shot" },
      { area: "writing", benchmark: "Arena-Hard", score: "39.4", note: "", secondary: true },
    ],
    blurb: "Large context window and reliable function-calling — a good fit for agent workflows.",
    tags: ["agents", "writing", "general"],
    quants: [
      { quant: "Q4_K_M", fileGB: 7.5, requiredGB: 9.0 },
      { quant: "Q8_0", fileGB: 13.0, requiredGB: 15.0 },
    ],
    runtimes: ["Ollama", "llama.cpp", "LM Studio"],
    ollamaTag: "mistral-nemo:12b",
    links: {
      github: "https://github.com/mistralai/mistral-inference",
      huggingface: "https://huggingface.co/mistralai/Mistral-Nemo-Instruct-2407",
      ollama: "https://ollama.com/library/mistral-nemo",
    },
  },
  {
    id: "mixtral-8x7b",
    name: "Mixtral",
    params: "8x7B",
    paramsB: 47,
    family: "Mistral",
    context: 32768,
    benchmarks: [],
    blurb: "Mixture-of-experts model — needs all experts in memory even though fewer are active per token.",
    tags: ["research", "writing"],
    quants: [
      { quant: "Q4_K_M", fileGB: 26.4, requiredGB: 30.4 },
      { quant: "Q8_0", fileGB: 49.6, requiredGB: 57.0 },
    ],
    runtimes: ["Ollama", "llama.cpp"],
    ollamaTag: "mixtral:8x7b",
    links: {
      github: "https://github.com/mistralai/mistral-inference",
      huggingface: "https://huggingface.co/mistralai/Mixtral-8x7B-Instruct-v0.1",
      ollama: "https://ollama.com/library/mixtral",
    },
  },

  {
    id: "phi35-mini",
    name: "Phi-3.5 Mini",
    params: "3.8B",
    paramsB: 3.8,
    family: "Phi",
    context: 131072,
    benchmarks: [
      { area: "coding", benchmark: "HumanEval", score: "62.8", note: "0-shot" },
      { area: "writing", benchmark: "MMLU", score: "69.0", note: "5-shot" },
    ],
    blurb: "Punches above its size on coding and reasoning benchmarks for its weight class.",
    tags: ["coding", "writing", "general"],
    quants: [
      { quant: "Q4_K_M", fileGB: 2.4, requiredGB: 3.9 },
      { quant: "Q8_0", fileGB: 4.1, requiredGB: 5.6 },
    ],
    runtimes: ["Ollama", "llama.cpp", "MLX"],
    ollamaTag: "phi3.5:3.8b",
    links: {
      github: "https://github.com/microsoft/Phi-3CookBook",
      huggingface: "https://huggingface.co/microsoft/Phi-3.5-mini-instruct",
      ollama: "https://ollama.com/library/phi3.5",
    },
  },
  {
    id: "phi4-mini",
    name: "Phi-4 Mini",
    params: "3.8B",
    paramsB: 3.8,
    family: "Phi",
    context: 131072,
    benchmarks: [
      { area: "research", benchmark: "MMLU", score: "67.3", note: "5-shot" },
      { area: "chat", benchmark: "Arena-Hard", score: "32.8", note: "" },
      { area: "research", benchmark: "GPQA", score: "25.2", note: "0-shot, CoT" },
    ],
    blurb: "Phi-4's smallest tier — strong reasoning-per-parameter, quick on modest hardware.",
    tags: ["writing", "general", "research", "chat"],
    quants: [
      { quant: "Q4_K_M", fileGB: 2.5, requiredGB: 4.0 },
      { quant: "Q8_0", fileGB: 4.1, requiredGB: 5.6 },
    ],
    runtimes: ["Ollama", "llama.cpp", "MLX"],
    ollamaTag: "phi4-mini:3.8b",
    links: {
      github: "https://github.com/microsoft/Phi-3CookBook",
      huggingface: "https://huggingface.co/microsoft/Phi-4-mini-instruct",
      ollama: "https://ollama.com/library/phi4-mini",
    },
  },
  {
    id: "phi4-14b",
    name: "Phi-4",
    params: "14B",
    paramsB: 14,
    family: "Phi",
    context: 16384,
    benchmarks: [
      { area: "research", benchmark: "MMLU", score: "84.8", note: "" },
      { area: "research", benchmark: "GPQA", score: "56.1", note: "" },
      { area: "coding", benchmark: "HumanEval", score: "82.6", note: "" },
    ],
    blurb: "Trained heavily on synthetic reasoning data — strong at math and structured problems. Notably shorter context than its Mini sibling.",
    tags: ["research", "coding"],
    quants: [
      { quant: "Q4_K_M", fileGB: 9.1, requiredGB: 10.6 },
      { quant: "Q8_0", fileGB: 15.6, requiredGB: 17.9 },
    ],
    runtimes: ["Ollama", "llama.cpp", "LM Studio"],
    ollamaTag: "phi4:14b",
    links: {
      github: "https://github.com/microsoft/Phi-3CookBook",
      huggingface: "https://huggingface.co/microsoft/phi-4",
      ollama: "https://ollama.com/library/phi4",
    },
  },

  {
    id: "gemma2-2b",
    name: "Gemma 2",
    params: "2B",
    paramsB: 2,
    family: "Gemma",
    context: 8192,
    benchmarks: [],
    blurb: "The smallest Gemma 2 tier — fast responses for lightweight chat and writing.",
    tags: ["writing", "chat", "general"],
    quants: [
      { quant: "Q4_K_M", fileGB: 1.7, requiredGB: 3.2 },
      { quant: "Q8_0", fileGB: 2.8, requiredGB: 4.3 },
    ],
    runtimes: ["Ollama", "llama.cpp", "LM Studio"],
    ollamaTag: "gemma2:2b",
    links: {
      github: "https://github.com/google-deepmind/gemma",
      huggingface: "https://huggingface.co/google/gemma-2-2b-it",
      ollama: "https://ollama.com/library/gemma2",
    },
  },
  {
    id: "gemma2-9b",
    name: "Gemma 2",
    params: "9B",
    paramsB: 9,
    family: "Gemma",
    context: 8192,
    benchmarks: [
      { area: "writing", benchmark: "MMLU", score: "71.3", note: "5-shot", secondary: true },
      { area: "chat", benchmark: "Arena-Hard", score: "43.7", note: "", secondary: true },
    ],
    blurb: "Well-tuned for natural conversation and everyday writing tasks.",
    tags: ["writing", "chat", "general"],
    quants: [
      { quant: "Q4_K_M", fileGB: 5.8, requiredGB: 7.3 },
      { quant: "Q8_0", fileGB: 9.8, requiredGB: 11.3 },
    ],
    runtimes: ["Ollama", "llama.cpp", "LM Studio"],
    ollamaTag: "gemma2:9b",
    links: {
      github: "https://github.com/google-deepmind/gemma",
      huggingface: "https://huggingface.co/google/gemma-2-9b-it",
      ollama: "https://ollama.com/library/gemma2",
    },
  },
  {
    id: "gemma2-27b",
    name: "Gemma 2",
    params: "27B",
    paramsB: 27,
    family: "Gemma",
    context: 8192,
    benchmarks: [],
    blurb: "The largest Gemma 2 tier — better nuance for long-form writing and analysis.",
    tags: ["writing", "research"],
    quants: [
      { quant: "Q4_K_M", fileGB: 16.6, requiredGB: 19.1 },
      { quant: "Q8_0", fileGB: 28.9, requiredGB: 33.2 },
    ],
    runtimes: ["Ollama", "llama.cpp", "LM Studio"],
    ollamaTag: "gemma2:27b",
    links: {
      github: "https://github.com/google-deepmind/gemma",
      huggingface: "https://huggingface.co/google/gemma-2-27b-it",
      ollama: "https://ollama.com/library/gemma2",
    },
  },

  {
    id: "codellama-7b",
    name: "Code Llama",
    params: "7B",
    paramsB: 7,
    family: "Code Llama",
    context: 16384,
    benchmarks: [],
    blurb: "The smallest Code Llama tier — a lightweight baseline for code completion.",
    tags: ["coding"],
    quants: [
      { quant: "Q4_K_M", fileGB: 4.1, requiredGB: 5.6 },
      { quant: "Q8_0", fileGB: 7.2, requiredGB: 8.7 },
    ],
    runtimes: ["Ollama", "llama.cpp", "LM Studio"],
    ollamaTag: "codellama:7b-instruct",
    links: {
      github: "https://github.com/meta-llama/codellama",
      huggingface: "https://huggingface.co/meta-llama/CodeLlama-7b-Instruct-hf",
      ollama: "https://ollama.com/library/codellama",
    },
  },
  {
    id: "codellama-13b",
    name: "Code Llama",
    params: "13B",
    paramsB: 13,
    family: "Code Llama",
    context: 16384,
    benchmarks: [],
    blurb: "Meta's dedicated code model — a reliable, older-generation coding baseline.",
    tags: ["coding"],
    quants: [
      { quant: "Q4_K_M", fileGB: 7.9, requiredGB: 9.4 },
      { quant: "Q8_0", fileGB: 13.8, requiredGB: 15.9 },
    ],
    runtimes: ["Ollama", "llama.cpp", "LM Studio"],
    ollamaTag: "codellama:13b-instruct",
    links: {
      github: "https://github.com/meta-llama/codellama",
      huggingface: "https://huggingface.co/meta-llama/CodeLlama-13b-Instruct-hf",
      ollama: "https://ollama.com/library/codellama",
    },
  },
  {
    id: "codellama-34b",
    name: "Code Llama",
    params: "34B",
    paramsB: 34,
    family: "Code Llama",
    context: 16384,
    benchmarks: [],
    blurb: "The largest Code Llama tier — stronger multi-file reasoning, needs a serious GPU or a lot of RAM.",
    tags: ["coding"],
    quants: [
      { quant: "Q4_K_M", fileGB: 20.2, requiredGB: 23.2 },
      { quant: "Q8_0", fileGB: 35.9, requiredGB: 41.3 },
    ],
    runtimes: ["Ollama", "llama.cpp", "LM Studio"],
    ollamaTag: "codellama:34b-instruct",
    links: {
      github: "https://github.com/meta-llama/codellama",
      huggingface: "https://huggingface.co/meta-llama/CodeLlama-34b-Instruct-hf",
      ollama: "https://ollama.com/library/codellama",
    },
  },

  {
    id: "starcoder2-3b",
    name: "StarCoder2",
    params: "3B",
    paramsB: 3,
    family: "StarCoder2",
    context: 16384,
    benchmarks: [
      { area: "coding", benchmark: "HumanEval", score: "31.7", note: "pass@1" },
      { area: "coding", benchmark: "DS-1000", score: "25.0", note: "pass@1" },
    ],
    blurb: "Fill-in-the-middle completion for IDE-style autocomplete — not tuned to follow chat instructions.",
    tags: ["coding"],
    quants: [
      { quant: "Q4_K_M", fileGB: 1.8, requiredGB: 3.3 },
      { quant: "Q8_0", fileGB: 3.2, requiredGB: 4.7 },
    ],
    runtimes: ["Ollama", "llama.cpp"],
    ollamaTag: "starcoder2:3b",
    links: {
      github: "https://github.com/bigcode-project/starcoder2",
      huggingface: "https://huggingface.co/bigcode/starcoder2-3b",
      ollama: "https://ollama.com/library/starcoder2",
    },
  },
  {
    id: "starcoder2-7b",
    name: "StarCoder2",
    params: "7B",
    paramsB: 7,
    family: "StarCoder2",
    context: 16384,
    benchmarks: [
      { area: "coding", benchmark: "HumanEval", score: "35.4", note: "pass@1" },
      { area: "coding", benchmark: "DS-1000", score: "27.8", note: "pass@1" },
    ],
    blurb: "A step up in completion quality over the 3B — still autocomplete, not a conversational assistant.",
    tags: ["coding"],
    quants: [
      { quant: "Q4_K_M", fileGB: 4.4, requiredGB: 5.9 },
      { quant: "Q8_0", fileGB: 7.6, requiredGB: 9.1 },
    ],
    runtimes: ["Ollama", "llama.cpp"],
    ollamaTag: "starcoder2:7b",
    links: {
      github: "https://github.com/bigcode-project/starcoder2",
      huggingface: "https://huggingface.co/bigcode/starcoder2-7b",
      ollama: "https://ollama.com/library/starcoder2",
    },
  },
  {
    id: "starcoder2-15b",
    name: "StarCoder2",
    params: "15B",
    paramsB: 15,
    family: "StarCoder2",
    context: 16384,
    benchmarks: [
      { area: "coding", benchmark: "HumanEval", score: "46.3", note: "pass@1" },
      { area: "coding", benchmark: "DS-1000", score: "33.8", note: "pass@1" },
    ],
    blurb: "Broad language coverage from The Stack v2 — still a completion model, not instruction-tuned like the Instruct release below.",
    tags: ["coding"],
    quants: [
      { quant: "Q4_K_M", fileGB: 9.9, requiredGB: 11.4 },
      { quant: "Q8_0", fileGB: 17.0, requiredGB: 19.6 },
    ],
    runtimes: ["Ollama", "llama.cpp"],
    ollamaTag: "starcoder2:15b",
    links: {
      github: "https://github.com/bigcode-project/starcoder2",
      huggingface: "https://huggingface.co/bigcode/starcoder2-15b",
      ollama: "https://ollama.com/library/starcoder2",
    },
  },
  {
    id: "starcoder2-15b-instruct",
    name: "StarCoder2 Instruct",
    params: "15B",
    paramsB: 15,
    family: "StarCoder2",
    context: 16384,
    benchmarks: [
      { area: "coding", benchmark: "HumanEval", score: "72.6", note: "pass@1" },
      { area: "coding", benchmark: "MBPP", score: "75.2", note: "pass@1" },
      { area: "coding", benchmark: "DS-1000", score: "40.6", note: "pass@1" },
    ],
    blurb: "BigCode's own instruction-tuned fine-tune of the 15B — actually follows coding prompts, unlike the base model above.",
    tags: ["coding"],
    quants: [
      { quant: "Q4_K_M", fileGB: 9.9, requiredGB: 11.4 },
      { quant: "Q8_0", fileGB: 17.0, requiredGB: 19.6 },
    ],
    runtimes: ["Ollama", "llama.cpp", "LM Studio"],
    ollamaTag: "starcoder2:15b-instruct",
    links: {
      github: "https://github.com/bigcode-project/starcoder2-self-align",
      huggingface: "https://huggingface.co/bigcode/starcoder2-15b-instruct-v0.1",
      ollama: "https://ollama.com/library/starcoder2",
    },
  },

  {
    id: "llava-16-7b",
    name: "LLaVA 1.6",
    params: "7B",
    paramsB: 7,
    family: "LLaVA",
    context: 4096,
    benchmarks: [],
    blurb: "Reads images alongside text — screenshots, diagrams, photos.",
    tags: ["vision", "general"],
    quants: [
      { quant: "Q4_K_M", fileGB: 4.5, requiredGB: 6.0 },
      { quant: "Q8_0", fileGB: 7.8, requiredGB: 9.3 },
    ],
    runtimes: ["Ollama", "llama.cpp"],
    ollamaTag: "llava:7b-v1.6",
    links: {
      github: "https://github.com/haotian-liu/LLaVA",
      huggingface: "https://huggingface.co/liuhaotian/llava-v1.6-mistral-7b",
      ollama: "https://ollama.com/library/llava",
    },
  },
  {
    id: "qwen2-vl-2b",
    name: "Qwen2-VL",
    params: "2B",
    paramsB: 2,
    family: "Qwen",
    context: 32768,
    benchmarks: [],
    blurb: "The smallest Qwen2-VL tier — fast image understanding for lightweight setups.",
    tags: ["vision", "general"],
    quants: [
      { quant: "Q4_K_M", fileGB: 1.0, requiredGB: 2.5 },
      { quant: "Q8_0", fileGB: 1.6, requiredGB: 3.1 },
    ],
    runtimes: ["Ollama", "llama.cpp"],
    links: {
      github: "https://github.com/QwenLM/Qwen2-VL",
      huggingface: "https://huggingface.co/Qwen/Qwen2-VL-2B-Instruct",
      ollama: "https://ollama.com/library/qwen2.5vl",
    },
  },
  {
    id: "qwen2-vl-7b",
    name: "Qwen2-VL",
    params: "7B",
    paramsB: 7,
    family: "Qwen",
    context: 32768,
    benchmarks: [
      { area: "vision", benchmark: "MMMU", score: "54.1", note: "val" },
      { area: "vision", benchmark: "DocVQA", score: "94.5", note: "test" },
    ],
    blurb: "Strong document and chart understanding in addition to general image Q&A.",
    tags: ["vision", "research"],
    quants: [
      { quant: "Q4_K_M", fileGB: 4.7, requiredGB: 6.2 },
      { quant: "Q8_0", fileGB: 8.1, requiredGB: 9.6 },
    ],
    runtimes: ["Ollama", "llama.cpp"],
    ollamaTag: "qwen2.5vl:7b",
    links: {
      github: "https://github.com/QwenLM/Qwen2-VL",
      huggingface: "https://huggingface.co/Qwen/Qwen2-VL-7B-Instruct",
      ollama: "https://ollama.com/library/qwen2.5vl",
    },
  },

  {
    id: "command-r-35b",
    name: "Command R",
    params: "35B",
    paramsB: 35,
    family: "Command R",
    context: 131072,
    benchmarks: [],
    blurb: "Built for retrieval-augmented generation and tool use with citation support.",
    tags: ["agents", "research"],
    quants: [
      { quant: "Q4_K_M", fileGB: 21.5, requiredGB: 24.7 },
      { quant: "Q8_0", fileGB: 37.2, requiredGB: 42.8 },
    ],
    runtimes: ["Ollama", "llama.cpp"],
    ollamaTag: "command-r:35b",
    links: {
      github: "https://github.com/cohere-ai/cohere-toolkit",
      huggingface: "https://huggingface.co/CohereLabs/c4ai-command-r-v01",
      ollama: "https://ollama.com/library/command-r",
    },
  },

  {
    id: "granite-4.1-3b",
    name: "IBM Granite",
    params: "3B",
    paramsB: 3,
    family: "Granite",
    context: 131072,
    benchmarks: [
      { area: "research", benchmark: "MMLU", score: "67.02", note: "5-shot" },
      { area: "research", benchmark: "GPQA", score: "31.70", note: "0-shot, CoT" },
      { area: "writing", benchmark: "IFEval", score: "82.30", note: "" },
    ],
    blurb: "IBM's dense 3B tier — built-in RAG and tool-calling without needing a fine-tune.",
    tags: ["agents", "coding", "writing", "general"],
    quants: [
      { quant: "Q4_K_M", fileGB: 2.2, requiredGB: 3.7 },
      { quant: "Q8_0", fileGB: 3.6, requiredGB: 5.1 },
    ],
    runtimes: ["Ollama", "llama.cpp"],
    ollamaTag: "granite4:3b",
    links: {
      github: "https://github.com/ibm-granite/granite-4.1-language-models",
      huggingface: "https://huggingface.co/ibm-granite/granite-4.1-3b",
      ollama: "https://ollama.com/library/granite4",
    },
  },
  {
    id: "granite-4.1-8b",
    name: "IBM Granite",
    params: "8B",
    paramsB: 8,
    family: "Granite",
    context: 131072,
    benchmarks: [
      { area: "research", benchmark: "MMLU", score: "73.84", note: "5-shot" },
      { area: "research", benchmark: "GPQA", score: "41.96", note: "0-shot, CoT" },
      { area: "writing", benchmark: "IFEval", score: "87.06", note: "" },
    ],
    blurb: "IBM's flagship dense Granite — tuned for tool-calling, RAG, and agentic tasks with a 128K context window.",
    tags: ["agents", "coding", "writing", "general"],
    quants: [
      { quant: "Q4_K_M", fileGB: 5.5, requiredGB: 7.0 },
      { quant: "Q8_0", fileGB: 9.3, requiredGB: 10.7 },
    ],
    runtimes: ["Ollama", "llama.cpp"],
    links: {
      github: "https://github.com/ibm-granite/granite-4.1-language-models",
      huggingface: "https://huggingface.co/ibm-granite/granite-4.1-8b",
      ollama: "https://ollama.com/library/granite4",
    },
  },

  {
    id: "ministral-3-3b",
    name: "Ministral 3",
    params: "3B",
    paramsB: 3,
    family: "Ministral",
    context: 262144,
    benchmarks: [
      { area: "chat", benchmark: "Arena-Hard", score: "30.5", note: "" },
      { area: "research", benchmark: "MATH", score: "83.0", note: "Maj@1" },
      { area: "vision", benchmark: "MM-MTBench", score: "7.83", note: "" },
    ],
    blurb: "The smallest Ministral 3 — reads images too, and fits comfortably on a laptop.",
    tags: ["chat", "agents", "research", "vision", "general"],
    quants: [
      { quant: "Q4_K_M", fileGB: 2.1, requiredGB: 3.6 },
      { quant: "Q8_0", fileGB: 3.7, requiredGB: 5.2 },
    ],
    runtimes: ["Ollama", "llama.cpp"],
    ollamaTag: "ministral-3:3b",
    links: {
      github: "https://github.com/mistralai/mistral-inference",
      huggingface: "https://huggingface.co/mistralai/Ministral-3-3B-Instruct-2512",
      ollama: "https://ollama.com/library/ministral-3",
    },
  },
  {
    id: "ministral-3-8b",
    name: "Ministral 3",
    params: "8B",
    paramsB: 8,
    family: "Ministral",
    context: 262144,
    benchmarks: [
      { area: "chat", benchmark: "Arena-Hard", score: "50.9", note: "" },
      { area: "research", benchmark: "MATH", score: "87.6", note: "Maj@1" },
      { area: "vision", benchmark: "MM-MTBench", score: "8.08", note: "" },
    ],
    blurb: "A balanced edge model with vision, native function-calling, and a 256K context window.",
    tags: ["chat", "agents", "research", "vision", "general"],
    quants: [
      { quant: "Q4_K_M", fileGB: 5.2, requiredGB: 6.7 },
      { quant: "Q8_0", fileGB: 9.0, requiredGB: 10.5 },
    ],
    runtimes: ["Ollama", "llama.cpp"],
    ollamaTag: "ministral-3:8b",
    links: {
      github: "https://github.com/mistralai/mistral-inference",
      huggingface: "https://huggingface.co/mistralai/Ministral-3-8B-Instruct-2512",
      ollama: "https://ollama.com/library/ministral-3",
    },
  },
  {
    id: "ministral-3-14b",
    name: "Ministral 3",
    params: "14B",
    paramsB: 14,
    family: "Ministral",
    context: 262144,
    benchmarks: [
      { area: "chat", benchmark: "Arena-Hard", score: "55.1", note: "" },
      { area: "research", benchmark: "MATH", score: "90.4", note: "Maj@1" },
      { area: "vision", benchmark: "MM-MTBench", score: "8.49", note: "" },
    ],
    blurb: "The largest Ministral 3 tier — same vision and agentic features, more headroom for complex tasks.",
    tags: ["chat", "agents", "research", "vision", "general"],
    quants: [
      { quant: "Q4_K_M", fileGB: 8.2, requiredGB: 9.7 },
      { quant: "Q8_0", fileGB: 14.4, requiredGB: 16.6 },
    ],
    runtimes: ["Ollama", "llama.cpp"],
    ollamaTag: "ministral-3:14b",
    links: {
      github: "https://github.com/mistralai/mistral-inference",
      huggingface: "https://huggingface.co/mistralai/Ministral-3-14B-Instruct-2512",
      ollama: "https://ollama.com/library/ministral-3",
    },
  },

  {
    id: "glm-4-9b-chat",
    name: "GLM-4",
    params: "9B",
    paramsB: 9,
    family: "GLM",
    context: 131072,
    benchmarks: [
      { area: "research", benchmark: "MMLU", score: "72.4", note: "" },
      { area: "coding", benchmark: "HumanEval", score: "71.8", note: "" },
      { area: "chat", benchmark: "MT-Bench", score: "8.35", note: "" },
    ],
    blurb: "Zhipu's dense 9B chat model with a 128K context window — a solid general-purpose option.",
    tags: ["chat", "writing", "general", "research", "coding"],
    quants: [
      { quant: "Q4_K_M", fileGB: 6.3, requiredGB: 7.8 },
      { quant: "Q8_0", fileGB: 10.0, requiredGB: 11.5 },
    ],
    runtimes: ["Ollama", "llama.cpp"],
    ollamaTag: "glm4:9b",
    links: {
      github: "https://github.com/zai-org/GLM-4",
      huggingface: "https://huggingface.co/zai-org/glm-4-9b-chat",
      ollama: "https://ollama.com/library/glm4",
    },
  },

  {
    id: "nemotron-3-nano-4b",
    name: "NVIDIA Nemotron 3 Nano",
    params: "4B",
    paramsB: 4,
    family: "Nemotron",
    context: 262144,
    benchmarks: [
      { area: "research", benchmark: "GPQA", score: "53.2", note: "reasoning-on" },
      { area: "agents", benchmark: "BFCL v3", score: "61.1", note: "" },
      { area: "chat", benchmark: "IFEval-Instruction", score: "88", note: "reasoning-off" },
    ],
    blurb: "NVIDIA's hybrid Mamba-attention model — trained on agentic, math, and competitive-programming data at a laptop-friendly size.",
    tags: ["coding", "research", "agents", "chat"],
    quants: [
      { quant: "Q4_K_M", fileGB: 3.0, requiredGB: 4.5 },
      { quant: "Q8_0", fileGB: 4.2, requiredGB: 5.7 },
    ],
    runtimes: ["Ollama", "llama.cpp"],
    ollamaTag: "nemotron-3-nano:4b",
    links: {
      github: "https://github.com/NVIDIA/NeMo",
      huggingface: "https://huggingface.co/nvidia/NVIDIA-Nemotron-3-Nano-4B-BF16",
      ollama: "https://ollama.com/library/nemotron-3-nano",
    },
  },

  {
    id: "hunyuan-7b-instruct",
    name: "Tencent Hunyuan",
    params: "7B",
    paramsB: 7,
    family: "Hunyuan",
    context: 32768,
    benchmarks: [
      { area: "research", benchmark: "GPQA-Diamond", score: "60.1", note: "" },
      { area: "coding", benchmark: "LiveCodeBench", score: "57.0", note: "" },
      { area: "writing", benchmark: "IF-Eval", score: "79.3", note: "" },
    ],
    blurb: "Tencent's dense 7B with hybrid fast/slow thinking modes for lighter or more complex reasoning.",
    tags: ["research", "coding", "writing", "general"],
    quants: [
      { quant: "Q4_K_M", fileGB: 4.6, requiredGB: 6.1 },
      { quant: "Q8_0", fileGB: 8.0, requiredGB: 9.5 },
    ],
    runtimes: ["llama.cpp"],
    links: {
      github: "https://github.com/Tencent-Hunyuan/Hunyuan-7B",
      huggingface: "https://huggingface.co/tencent/Hunyuan-7B-Instruct",
    },
  },

  {
    id: "ernie-4.5-0.3b",
    name: "Baidu ERNIE 4.5",
    params: "0.3B",
    paramsB: 0.3,
    family: "ERNIE",
    context: 131072,
    benchmarks: [],
    blurb: "Baidu's smallest ERNIE tier — tiny footprint, best for quick lookups rather than nuanced writing.",
    tags: ["chat", "general"],
    quants: [
      { quant: "Q4_K_M", fileGB: 0.2, requiredGB: 1.7 },
      { quant: "Q8_0", fileGB: 0.4, requiredGB: 1.9 },
    ],
    runtimes: ["llama.cpp"],
    links: {
      github: "https://github.com/PaddlePaddle/ERNIE",
      huggingface: "https://huggingface.co/baidu/ERNIE-4.5-0.3B-PT",
    },
  },
  {
    id: "ernie-4.5-21b-a3b-thinking",
    name: "Baidu ERNIE 4.5 Thinking",
    params: "21B-A3B",
    paramsB: 21,
    family: "ERNIE",
    context: 131072,
    benchmarks: [],
    blurb: "A mixture-of-experts reasoning specialist — 21B total parameters, only 3B active per token, so it's lighter to run than the size suggests.",
    tags: ["research", "coding"],
    quants: [
      { quant: "Q4_K_M", fileGB: 13.5, requiredGB: 15.5 },
      { quant: "Q8_0", fileGB: 23.2, requiredGB: 26.7 },
    ],
    runtimes: ["llama.cpp"],
    links: {
      github: "https://github.com/PaddlePaddle/ERNIE",
      huggingface: "https://huggingface.co/baidu/ERNIE-4.5-21B-A3B-Thinking",
    },
  },

  {
    id: "gemma3-1b",
    name: "Gemma 3",
    params: "1B",
    paramsB: 1,
    family: "Gemma",
    context: 32768,
    benchmarks: [],
    blurb: "The smallest Gemma 3 tier — text only, fast on modest hardware.",
    tags: ["writing", "chat", "general"],
    quants: [
      { quant: "Q4_K_M", fileGB: 0.8, requiredGB: 2.3 },
      { quant: "Q8_0", fileGB: 1.1, requiredGB: 2.6 },
    ],
    runtimes: ["Ollama", "llama.cpp", "LM Studio", "MLX"],
    ollamaTag: "gemma3:1b",
    links: {
      github: "https://github.com/google-deepmind/gemma",
      huggingface: "https://huggingface.co/google/gemma-3-1b-it",
      ollama: "https://ollama.com/library/gemma3",
    },
  },
  {
    id: "gemma3-4b",
    name: "Gemma 3",
    params: "4B",
    paramsB: 4,
    family: "Gemma",
    context: 131072,
    benchmarks: [],
    blurb: "Adds vision to the Gemma 3 line at a laptop-friendly size, with a 128K context window.",
    tags: ["writing", "chat", "general", "vision"],
    quants: [
      { quant: "Q4_K_M", fileGB: 2.5, requiredGB: 4.0 },
      { quant: "Q8_0", fileGB: 4.1, requiredGB: 5.6 },
    ],
    runtimes: ["Ollama", "llama.cpp", "LM Studio", "MLX"],
    ollamaTag: "gemma3:4b",
    links: {
      github: "https://github.com/google-deepmind/gemma",
      huggingface: "https://huggingface.co/google/gemma-3-4b-it",
      ollama: "https://ollama.com/library/gemma3",
    },
  },
  {
    id: "gemma3-12b",
    name: "Gemma 3",
    params: "12B",
    paramsB: 12,
    family: "Gemma",
    context: 131072,
    benchmarks: [],
    blurb: "A stronger vision-capable Gemma 3 tier for more demanding writing and analysis tasks.",
    tags: ["writing", "chat", "general", "vision"],
    quants: [
      { quant: "Q4_K_M", fileGB: 7.3, requiredGB: 8.8 },
      { quant: "Q8_0", fileGB: 12.5, requiredGB: 14.4 },
    ],
    runtimes: ["Ollama", "llama.cpp", "LM Studio", "MLX"],
    ollamaTag: "gemma3:12b",
    links: {
      github: "https://github.com/google-deepmind/gemma",
      huggingface: "https://huggingface.co/google/gemma-3-12b-it",
      ollama: "https://ollama.com/library/gemma3",
    },
  },
  {
    id: "gemma3-27b",
    name: "Gemma 3",
    params: "27B",
    paramsB: 27,
    family: "Gemma",
    context: 131072,
    benchmarks: [],
    blurb: "The largest Gemma 3 tier — vision-capable with the most headroom for long-form analysis.",
    tags: ["writing", "chat", "general", "vision"],
    quants: [
      { quant: "Q4_K_M", fileGB: 16.5, requiredGB: 19.0 },
      { quant: "Q8_0", fileGB: 28.7, requiredGB: 33.0 },
    ],
    runtimes: ["Ollama", "llama.cpp", "LM Studio", "MLX"],
    ollamaTag: "gemma3:27b",
    links: {
      github: "https://github.com/google-deepmind/gemma",
      huggingface: "https://huggingface.co/google/gemma-3-27b-it",
      ollama: "https://ollama.com/library/gemma3",
    },
  },

  {
    id: "gemma4-e2b",
    name: "Gemma 4",
    params: "E2B",
    paramsB: 5.1,
    family: "Gemma",
    context: 131072,
    benchmarks: [],
    blurb: "The smallest Gemma 4 tier — omni-modal (text, image, audio) with configurable reasoning, built for on-device use.",
    tags: ["coding", "research", "agents", "chat", "vision", "general"],
    quants: [
      { quant: "Q4_K_M", fileGB: 3.5, requiredGB: 5.0 },
      { quant: "Q8_0", fileGB: 5.0, requiredGB: 6.5 },
    ],
    runtimes: ["Ollama", "llama.cpp", "LM Studio", "MLX"],
    ollamaTag: "gemma4:e2b",
    links: {
      github: "https://github.com/google-gemma",
      huggingface: "https://huggingface.co/google/gemma-4-E2B-it",
      ollama: "https://ollama.com/library/gemma4",
    },
  },
  {
    id: "gemma4-e4b",
    name: "Gemma 4",
    params: "E4B",
    paramsB: 8,
    family: "Gemma",
    context: 131072,
    benchmarks: [],
    blurb: "A step up from E2B with the same omni-modal support — more headroom for complex reasoning tasks.",
    tags: ["coding", "research", "agents", "chat", "vision", "general"],
    quants: [
      { quant: "Q4_K_M", fileGB: 5.0, requiredGB: 6.5 },
      { quant: "Q8_0", fileGB: 8.2, requiredGB: 9.7 },
    ],
    runtimes: ["Ollama", "llama.cpp", "LM Studio", "MLX"],
    ollamaTag: "gemma4:e4b",
    links: {
      github: "https://github.com/google-gemma",
      huggingface: "https://huggingface.co/google/gemma-4-E4B-it",
      ollama: "https://ollama.com/library/gemma4",
    },
  },
  {
    id: "gemma4-12b-unified",
    name: "Gemma 4",
    params: "12B Unified",
    paramsB: 12,
    family: "Gemma",
    context: 262144,
    benchmarks: [],
    blurb: "Encoder-free \"Unified\" architecture — native audio and vision understanding without separate encoders, at a 256K context window.",
    tags: ["coding", "research", "agents", "chat", "vision", "general"],
    quants: [
      { quant: "Q4_K_M", fileGB: 7.1, requiredGB: 8.6 },
      { quant: "Q8_0", fileGB: 12.7, requiredGB: 14.6 },
    ],
    runtimes: ["Ollama", "llama.cpp", "LM Studio", "MLX"],
    ollamaTag: "gemma4:12b",
    links: {
      github: "https://github.com/google-gemma",
      huggingface: "https://huggingface.co/google/gemma-4-12B-it",
      ollama: "https://ollama.com/library/gemma4",
    },
  },
  {
    id: "gemma4-26b-a4b",
    name: "Gemma 4",
    params: "26B MoE",
    paramsB: 26,
    family: "Gemma",
    context: 262144,
    benchmarks: [],
    blurb: "Mixture-of-experts Gemma 4 — 26B total parameters with only 4B active per token, plus a 256K context window.",
    tags: ["coding", "research", "agents", "chat", "vision", "general"],
    quants: [
      { quant: "Q4_K_M", fileGB: 16.9, requiredGB: 19.4 },
      { quant: "Q8_0", fileGB: 26.9, requiredGB: 30.9 },
    ],
    runtimes: ["Ollama", "llama.cpp", "LM Studio", "MLX"],
    ollamaTag: "gemma4:26b",
    links: {
      github: "https://github.com/google-gemma",
      huggingface: "https://huggingface.co/google/gemma-4-26B-A4B-it",
      ollama: "https://ollama.com/library/gemma4",
    },
  },
];

const USE_CASES = [
  { id: "coding", label: "Coding" },
  { id: "research", label: "Research & analysis" },
  { id: "writing", label: "Writing" },
  { id: "chat", label: "General chat" },
  { id: "agents", label: "Agents & tool use" },
  { id: "vision", label: "Vision & images" },
];
